#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
mylog="/var/log/$(basename $0).log"
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
lock1="/var/lib/dpkg/lock"
lock2="/var/lib/apt/lists/lock"
gdonde="/home/$quien/.gnupg/gpg.conf"
mdir=(/usr /var /home /bin /etc)
rotos="/tmp/rotos.txt"
source /usr/bin/mivariable
function clean_1() {
	rm -f /run/$(basename $0).pid
	rm -rf /tmp/*
	rm -rf /var/tmp/*
	rm -f $LOCKFILE
	rm -f $lock1
	rm -f $lock2
	rm -f /root/.sinfallas/actualizar
	killall -I -q apt dpkg aria2c apt-fast dpkg-deb prelink.bin freshclam rkhunter flatpak
	dpkg --configure -a
}
function myupdate_1() {
	echo -e "\e[00;1;92mIniciando Actualizacion\e[00m"
	echo "inicio" > /root/.sinfallas/actualizar
	if [[ -z $(grep -i "$nrconf{restart} = 'a';" /etc/needrestart/needrestart.conf) ]]; then
		echo "\$nrconf{restart} = 'a';" >> /etc/needrestart/needrestart.conf
	fi
	chmod 644 /etc/apt/trusted.gpg.d/*
	echo "_APTMGR=apt" > /etc/apt-fast.conf
	echo "DOWNLOADBEFORE=true" >> /etc/apt-fast.conf
	echo "#MIRRORS=( 'http://mirror.uchile.cl/ubuntu/,http://mirror.ufam.edu.br/ubuntu/,https://mirror.ufro.cl/ubuntu/,http://ubuntu.mti.mt.gov.br/,http://ubuntu.c3sl.ufpr.br/ubuntu/,http://ubuntu-archive.locaweb.com.br/ubuntu/,https://ubuntu.repo.cure.edu.uy/mirror/,https://mirror.uepg.br/ubuntu/,https://edgeuno-bog2.mm.fcix.net/ubuntu/,http://repos.interior.edu.uy/ubuntu/,http://mirror.unimagdalena.edu.co/ubuntu/,https://mirror.hnd.cl/ubuntu/,http://ubuntu.unc.edu.ar/ubuntu/,http://mirror.cedia.org.ec/ubuntu/,http://sft.if.usp.br/ubuntu/,https://mirrors.dc.clear.net.ar/ubuntu/,http://mirror.ufscar.br/ubuntu/,https://ubuntu.itsbrasil.net/ubuntu/,http://mirrors.eze.sysarmy.com/ubuntu/,,https://ubuntu.letscloud.io/ubuntu/,https://ubuntu.zero.com.ar/ubuntu/,http://archive.ubuntu.com/ubuntu/' )" >> /etc/apt-fast.conf
	echo "_MAXNUM=10" >> /etc/apt-fast.conf
	echo "_MAXCONPERSRV=10" >> /etc/apt-fast.conf
	echo "_SPLITCON=8" >> /etc/apt-fast.conf
	echo "_MINSPLITSZ=1M" >> /etc/apt-fast.conf
	echo "_PIECEALGO=default" >> /etc/apt-fast.conf
	echo "DLLIST='/tmp/apt-fast.list'" >> /etc/apt-fast.conf
	echo "_DOWNLOADER='aria2c --no-conf -c -j "'${_MAXNUM}'" -x "'${_MAXCONPERSRV}'" -s "'${_SPLITCON}'" --min-split-size="'${_MINSPLITSZ}'" --stream-piece-selector="'${_PIECEALGO}'" -i "'${DLLIST}'" --connect-timeout=600 --timeout=600 -m0 --header "'"Accept: */*"'"'" >> /etc/apt-fast.conf
	echo "DLDIR='/var/cache/apt/apt-fast'" >> /etc/apt-fast.conf
	echo "APTCACHE='/var/cache/apt/archives'" >> /etc/apt-fast.conf
	echo "cGreen='\e[0;32m'" >> /etc/apt-fast.conf
	echo "cRed='\e[0;31m'" >> /etc/apt-fast.conf
	echo "cBlue='\e[0;34m'" >> /etc/apt-fast.conf
	echo "xendColor='\e[0m'" >> /etc/apt-fast.conf
	rm -f $lock1
	rm -f $lock2
	echo -e "\e[00;1;92m(1/14) Actualizando paquetes FLATPAK\e[00m"
	flatpak update
	echo -e "\e[00;1;92m(2/14) Actualizando paquetes DEB\e[00m"
	apt-fast -q update
	errores
	apt-fast -y install actualizar
	errores
	apt-fast -q update
	errores
	apt-fast -y dist-upgrade
	errores	
	echo -e "\e[00;1;92m(3/14) Actualizando firmas de virus de ClamAV\e[00m"
	sed -i 's\ReceiveTimeout.*\ReceiveTimeout 3600\g' /etc/clamav/freshclam.conf
	killall -q freshclam
	mkdir -p /var/log/clamav
	touch /var/log/clamav/freshclam.log
	chmod 666 /var/log/clamav/freshclam.log
	chown -R clamav:clamav /var/log/clamav
	freshclam
	errores
	echo -e "\e[00;1;92m(4/14) Actualizando firmas de RKHunter\e[00m"
	rkhunter --versioncheck
	rkhunter --update --propupd
	errores
	echo -e "\e[00;1;92m(5/14) Actualizando Metadatos de Firmware Updater\e[00m"
	fwupdmgr refresh --force
	echo -e "\e[00;1;92m(6/14) Limpiando historial\e[00m"
	cleanfish
	echo -e "\e[00;1;92m(7/14) Limpiando paquetes\e[00m"
	cleanpkg
	echo -e "\e[00;1;92m(9/14) Grub\e[00m"
	update-grub2
	errores
	update-initramfs -c -k all
	errores
	echo -e "\e[00;1;92m(10/14) Limpiando Caches\e[00m"
	cleancache
	echo -e "\e[00;1;92m(11/14) Limpiando symlinks rotos,\e[00m"
	for j in ${mdir[@]}; do
		echo "Limpiando $j"
		cd $j
		find . -type l -exec sh -c 'file -b "$1" | grep -q ^broken' sh {} \; -print > $rotos
		for i in $(cat $rotos); do
			rm -f $i
		done
	done
	rm -f $rotos
	echo -e "\e[00;1;92m(12/14) Deteniendo servicios innecesarios\e[00m"
	myservices
	if [[ $(dpkg --get-selections | grep -w "mikvm" | awk '{print $1}' | head -1) = mikvm ]]; then
		if [[ -f /root/.sinfallas/novirt.custom ]]; then
			source /usr/bin/milanzador -k off
		fi
	fi
	rm -f /root/.sinfallas/actualizar
}

trap "clean_1; exit" 0 1 2 3 9 15
siroot
echo $BASHPID > /run/"$(basename $0)".pid
echo "" > $mylog
exec 2>>$mylog
lock || exit_error

case "$1" in
	auto)
		myupdate_1
		echo -e "\e[00;1;92mFinalizado.\e[00m"
	;;

	*)
		echo "El equipo podria reiniciarse automaticamente, por favor guarde antes de continuar."
		pause
		clear
		myupdate_1
		echo -e "\e[00;1;92m(13/14) Los siguientes archivos fueron modificados por fuera de procesos de instalacion / actualizacion\e[00m"
		echo ""
		debsums -sc
		echo ""
		echo -e "\e[00;1;92m(14/14) Verificacion final\e[00m"
		needrestart -r a
		echo -e "\e[00;1;92mFinalizado.\e[00m"
	;;

esac
exit 0
